LPS-12345
pedroamarall/liferay-portal pull request #13
Opened 2023-09-21 15:22 UTC by Youness-ELMO

2023-09-21 16:45 UTC, pedroamarall commented
ci:test:sf

2023-09-21 16:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8233/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8233/jenkins-report.html">here</a>.</b></p>

2023-09-21 16:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e716e8827644e1619318501f5d5243dea45fe8b">6e716e8827644e1619318501f5d5243dea45fe8b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Youness-ELMO/liferay-portal/tree/LPS-12345-Poshi-exercises">LPS-12345-Poshi-exercises</a><br/>Branch GIT ID: <a href="https://github.com/Youness-ELMO/liferay-portal/commit/68057fd6266d744de5022dc48316cac44759a32a">68057fd6266d744de5022dc48316cac44759a32a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8233/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8233/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: Variable 'Item' in 'ValidateConfigurationStringAtControlPanel' should start with a lowercase letter: /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase (SourceCheck:PoshiVariableNameCheck)
     [java] 2: /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/Path/FileTest.path expected:&lt;...d&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] [&lt;tr&gt;
     [java]   &lt;td&gt;CLICK_CTP&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="_com_liferay_product_navigation_applications_menu_web_internal_portlet_ProductNavigationApplicationsMenuPortlet_tab_2"]/button&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;CHECK_CONF&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="nav_control_panel.configuration"]&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] 
     [java] &lt;!-- Part of Screen size --&gt;
     [java] 
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;CLICK_SIMULATION&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_simulationToggleId"]&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;CLICK_CUSTOM&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_simulationDeviceContainer"]/div/div[1]/button[5]&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;INPUT_WIDTH&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_width"]&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;INPUT_HEIGHT&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_height"]&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;]
     [java] 
     [java] &lt;/tbody&gt;
     [java] &lt;/table&gt;
     [java] ...&gt; but was:&lt;...d&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] [
     [java] 
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;CLICK_CTP&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="_com_liferay_product_navigation_applications_menu_web_internal_portlet_ProductNavigationApplicationsMenuPortlet_tab_2"]/button&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] 
     [java] 
     [java] 
     [java] &lt;tr&gt;
     [java]   &lt;td&gt;CHECK_CONF&lt;/td&gt;
     [java]   &lt;td&gt;//*[@id="nav_control_panel.configuration"]&lt;/td&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;</pre></details></html>

2023-09-21 16:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8233/">test-portal-source-format#8233</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8233/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/13">pedroamarall#13</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2428926833">[master] ci:test:sf - Youness-ELMO &gt; pedroamarall - PR#13 - 2023-09-21[09:45:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/31259/">publish-testray-report#31259</a><br/></div></div>

2023-09-22 08:47 UTC, pedroamarall commented
ci:reopen

2023-09-22 08:47 UTC, pedroamarall commented
ci:help

2023-09-22 08:47 UTC, liferay-continuous-integration commented
## Available CI commands:
#### ci:close
&nbsp;&nbsp;&nbsp;&nbsp;Close the pull request.
#### ci:forward[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request  and forward the pull request to `brianchandotcom` if the required test suites pass for `ci:forward` or complete for `ci:forward:force`.
#### ci:merge[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Merge in the changes from the subrepo. All tests must pass before this command will successfully run. Optionally use the force flag to bypass failed tests.
#### ci:reevaluate:[buildID]
&nbsp;&nbsp;&nbsp;&nbsp;Reevaluate the pull request result from a generated build ID.
#### ci:reopen
&nbsp;&nbsp;&nbsp;&nbsp;Reopen the pull request.
#### ci:stop[:suite]
&nbsp;&nbsp;&nbsp;&nbsp;Stop all currrently running tests. Optionally specify the name of the test suite.
#### ci:test[:suite][:SHA|nocompile|norebase|gist-SHA]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request. Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.
<details><summary><strong>Available test suites:</strong></summary>

- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional-db-partition** - Test acceptance functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-release** - Compile a release bundle and execute acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility** - Test all accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility-menu** - Test all accessibility menu tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-acceptance** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-integration** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-servers** - Test Deployments on App Servers.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clay** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**comment** - Test Comment tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-database** - Test only Commerce Database tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es8-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 8 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-integration** - Test only Commerce integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-upgrade** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**continuous-integration** - Test Continuous Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**cookies** - Test Cookie Preferences tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine-db-partition** - Test Data Engine functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration** - Test only Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration-functional** - Test only functional Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**db-partition** - Test Database Partitioning functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document-antivirus** - Test Antivirus against DM.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-accessibility** - Test Echo (WCM) team accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-analytics-cloud** - Test segmentation and personalization with Analytics Cloud.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-db-partition** - Test Echo (WCM) team acceptance tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-headless** - Test Echo (WCM) team headless components.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-db-partition** - Test forms functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**friendly-url** - Test Friendly URL tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test all Frontend Infra team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-client-extensions** - Test frontend client extensions tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-data-set** - Test frontend data set tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-dev-exp** - Test frontend developer experience tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-ui** - Test frontend ui tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-walkthrough** - Test frontend walkthrough tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test all headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-builder** - All tests for Headless Builder component.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-functional** - Headless Team functional API tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**hotel** - Test all Source Formatter unit tests related to upgrade
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**item-selector** - Test item selecto [...]

2023-09-22 16:30 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +
Done

2023-09-22 16:31 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +    macro ClickMenu {
Done

2023-09-22 16:31 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +    macro ClickSimulation {
Fixed, thanks for the comment

2023-09-22 16:32 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +    }
done

2023-09-22 16:32 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +    }
done

2023-09-22 16:32 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +    // Ex 2: Part of form
thanks, its done

2023-09-22 16:34 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +    }
oops, I forget, let me fix it, sorry!

2023-09-22 16:34 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +// Extra exercise : Blog Part
done

2023-09-22 16:35 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +    // }
oky i fixe it

2023-09-22 16:35 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +}
done

2023-09-22 16:36 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +    }
ohhh thank you , yes i change the task description

2023-09-22 16:55 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +    }
when i do the formating, he don't delete the spaces so i need to fix it manually !!

2023-09-25 09:44 UTC, pedroamarall commented
ci:test:sf

2023-09-25 09:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/2993/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2993/jenkins-report.html">here</a>.</b></p>

2023-09-25 09:48 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Youness-ELMO/liferay-portal/tree/LPS-12345-Poshi-exercises">LPS-12345-Poshi-exercises</a><br/>Branch GIT ID: <a href="https://github.com/Youness-ELMO/liferay-portal/commit/3eb036238cfa49ea81d61e55892b0dade271626e">3eb036238cfa49ea81d61e55892b0dade271626e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2993/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2993/jenkins-report.html">here</a>.</h5></details></html>

2023-09-25 09:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2993/">test-portal-source-format#2993</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2993/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/13">pedroamarall#13</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430291726">[master] ci:test:sf - Youness-ELMO &gt; pedroamarall - PR#13 - 2023-09-25[02:44:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/11577/">publish-testray-report#11577</a><br/></div></div>

2023-09-25 10:27 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +	macro clickOnForm {
A more appropriate name would be "CreateForm" because this macro is not just clicking, its function is to create a form, correct?

2023-09-25 10:27 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +			TestTraining.VerifyCONF(item = "CONFIGURATION");
Use BDD correctly please (GIVEN, WHEN and THEN)

2023-09-25 10:27 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		ApplicationsMenuHelper.openApplicationsMenu();
Why did you create a macro that already does this?

2023-09-25 10:27 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
Your test is just 1 macro?

2023-09-25 10:27 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
You could divide this macro into several parts since I saw that it performs several functions, as you can use it in other tests and you can also organize your test case with BDD

2023-09-25 14:26 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +	macro clickOnForm {
done

2023-09-25 14:26 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +			TestTraining.VerifyCONF(item = "CONFIGURATION");
Done

2023-09-25 14:27 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +	macro clickOnForm {
Done

2023-09-25 14:28 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		ApplicationsMenuHelper.openApplicationsMenu();
done

2023-09-25 14:28 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
sorry for this one just a test i fix it, thank you

2023-09-25 14:29 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
safi its done, i split it to many tasks

2023-09-25 17:35 UTC, manoelcyreno commented
starting the review :eyes:

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/Path/FileTest.path
> +	<td>//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_simulationDeviceContainer"]/div/div[1]/button[5]</td>
This locator is using a mix between an absolute and relative XPath, please, change it to use the **relative xpath** in the right way

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		FormViewBuilder.clickFieldLabel(fieldLabel = "Age");
add a new line between those lines

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		FormFields.editText(
add a new line between those lines

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		FormFields.editText(
add a new line between those lines

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	property testray.main.component.name = "Forms";
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		TestCase.setUpPortalInstance();
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		User.firstLoginPG();
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	tearDown {
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		if (${testPortalInstance} == "true") {
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
duplicated lines.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		}
Replace it with a JSON call about creating a blog.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
duplicated code

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
duplicated code

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +				entryTitle = "This is Title");
Replace it with a JSON call about creating a blog.

2023-09-25 17:54 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		}
Replace it with a JSON call about creating a blog.

2023-09-25 17:56 UTC, manoelcyreno commented
@Youness-ELMO, take a look at:
1- all "Given", "When", "Then", and "And" that you created, in some cases, are in lower cases, in other all character is in higher case...
2- The name of your methods, and the "Then", do not pass to me what in fact it wants to validate... so, please, change it.
3- Review all the comments above.

2023-09-25 17:59 UTC, manoelcyreno requested changes
request changes on the PR

2023-09-26 14:39 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/Path/FileTest.path
> +	<td>//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_simulationDeviceContainer"]/div/div[1]/button[5]</td>
Done

2023-09-26 14:40 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		FormFields.editText(
Done

2023-09-26 14:40 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		FormFields.editText(
Done

2023-09-26 14:41 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	property testray.main.component.name = "Forms";
sorry for those duplicated lines, yesterday I merged some files and it showed me these duplicate lines, I fixed the duplicate lines, thank you!

2023-09-26 14:42 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		TestCase.setUpPortalInstance();
Done

2023-09-26 14:42 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
Done

2023-09-26 14:42 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	tearDown {
Done

2023-09-26 14:42 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		User.firstLoginPG();
Done

2023-09-26 14:42 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		if (${testPortalInstance} == "true") {
Done

2023-09-26 14:42 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
Done

2023-09-26 14:43 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		}
Done, it a new information thank you!

2023-09-26 14:43 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
Done

2023-09-26 14:43 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +	}
fixed, thank you!

2023-09-26 14:43 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		}
done

2023-09-26 14:44 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +				entryTitle = "This is Title");
Done

2023-09-26 14:55 UTC, Youness-ELMO commented
> @Youness-ELMO, take a look at: 1- all "Given", "When", "Then", and "And" that you created, in some cases, are in lower cases, in other all character is in higher case... 2- The name of your methods, and the "Then", do not pass to me what in fact it wants to validate... so, please, change it. 3- Your code is about Blogs or Forms? in only 1 testcase file, you added test code, about these 2 different components/features... split it. 4- Review all the comments above.

@manoelcyreno  Thank you for your comments, actually I fixed almost all of those errors, the problem is I didn't understand the second request [2- The name of your methods, and the "Then", do not pass to me what in fact it wants to validate... so, please, change it."], what i need to do in "Then" tasks exactly, thanks for your time, have a great day!

2023-09-26 14:55 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/macro/TestTraining.macro
> +		FormViewBuilder.clickFieldLabel(fieldLabel = "Age");
Done

2023-10-02 10:31 UTC, manoelcyreno requested changes

2023-10-02 10:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +		}
GIVEN / WHEN / then

Is this look right? this is following some pattern?

2023-10-02 10:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myTestPoshi/testcase/MyTestFile.testcase
> +			TestTraining.VerifyCONF(item = "CONFIGURATION");
Why do you create a macro for it?  Why didn't you add the assert here?

2023-10-02 10:36 UTC, manoelcyreno commented
@Youness-ELMO, take a look at:
1- all "Given", "When", "Then", and "And" that you created, in some cases, are in lower cases, in other all character is in higher case...
2- The name of your methods, and the "Then", do not pass to me what it wants to validate... so, please, change it.
3- Review all the comments above.


example about the point 2.

> "Then Verify the results"
Verify what? fail situation? success situation?

> test CreateForm
Create with success? with failure? is not possible to create? is possible?

Think about a person without any context who will read it and this person will understand what you want to test, without reading your code in details?

2023-10-03 09:20 UTC, closed without merging