LPS 212337
pedroamarall/liferay-portal pull request #21
Opened 2023-09-22 09:03 UTC by younes2123

2023-09-22 15:46 UTC, pedroamarall commented
ci:test:sf

2023-09-22 15:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7381/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7381/jenkins-report.html">here</a>.</b></p>

2023-09-22 15:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f31084975b8217be699b430883a9f0a97c1eefc">2f31084975b8217be699b430883a9f0a97c1eefc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/younes2123/liferay-portal/tree/LPS-212337">LPS-212337</a><br/>Branch GIT ID: <a href="https://github.com/younes2123/liferay-portal/commit/c8a7ac86d2bc48717af562cdf863f39bfef8d03d">c8a7ac86d2bc48717af562cdf863f39bfef8d03d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7381/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7381/jenkins-report.html">here</a>.</h5></details></html>

2023-09-22 15:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7381/">test-portal-source-format#7381</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7381/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/21">pedroamarall#21</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2429701068">[master] ci:test:sf - younes2123 &gt; pedroamarall - PR#21 - 2023-09-22[08:46:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27505/">publish-testray-report#27505</a><br/></div></div>

2023-09-25 10:39 UTC, pedroamarall commented
Hello @younes2123, you already have an [open pr](https://github.com/pedroamarall/liferay-portal/pull/14) with the same files, could you put these changes in the pr that is open please

2023-09-25 12:50 UTC, younes2123 commented
> Hello @younes2123, you already have an [open pr](https://github.com/pedroamarall/liferay-portal/pull/14) with the same files, could you put these changes in the pr that is open please

I closed the old one.

2023-09-25 18:14 UTC, manoelcyreno requested changes
@younes2123 , take a look at:
1- The name of your methods, and the "Then", do not pass to me what in fact it wants to validate... so, please, change it.
2- You didn't add any assert
3- you didn't add tasks in a lot of cases
4- Review all the comments above.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/paths/PanelTest.path
> +	<td>//*[contains(@class, 'dropdown-toggle lfr-portal-tooltip btn btn-monospaced btn-sm btn-unstyled')]</td>
This locator is a bad practice, cuz you are saying that the classes need to be defined in that order .. if the programmer changes the order your locator will fail, so please, use a better relative XPath to it.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/paths/PanelTest.path
> +	<td>//li[contains(@id, '_com_liferay_product_navigation_applications_menu_web_internal_portlet_ProductNavigationApplicationsMenuPortlet_tab_2')]</td>
why are you defining the "li" here?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/paths/PanelTest.path
> +	<td>//h2[contains(@id, 'nav_control_panel.configuration')]</td>
why are you defining the "h2" here?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/paths/PanelTest.path
> +	<td>//*[@id="_com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet_simulationDeviceContainer"]/div/div/button[5]</td>
This locator is using a mix between an absolute and relative XPath, please, change it to use the **relative xpath** in the right way

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +			entryTitle = ${entryTitle});
change it to a parameter that the user will pass on the testcase file.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +			rowEntry = "Blogs Entry Title");
change it to a parameter that the user will pass on the testcase file.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +			rowEntry = "Blogs Entry Title");
change it to a parameter that the user will pass on the testcase file.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +			entryTitleEdit = "New title");
change it to a parameter that the user will pass on the testcase file.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +			entryTitle = "Blogs Entry Title",
change it to a parameter that the user will pass on the testcase file.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +			entryTitle = "Blogs Entry Title");
change it to a parameter that the user will pass on the testcase file.

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyBlogsTests.testcase
> +	}
where are the "assert" to validate if it is right or not?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyBlogsTests.testcase
> +	}
where are the "assert" to validate if it is right or not?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyBlogsTests.testcase
> +	}
where are the "assert" to validate if it is right or not?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyBlogsTests.testcase
> +	}
where are the "assert" to validate if it is right or not?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyTestFile.testcase
> +	}
where are the tasks?

2023-09-25 18:14 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/NewForms.testcase
> +			rowEntry = "Younes Fatihi");
refactor all that test to use JSON calls, the test (by UI) needs to do, exactly what you want to validate, not the "setup" of your test.
add tasks to your code to be understandable ....

2023-10-02 16:30 UTC, younes2123 commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyBlogsTests.testcase
> +	}
Fixed, please check the last commits

2023-10-02 16:30 UTC, younes2123 commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyTestFile.testcase
> +	}
Fixed, please check the last commits

2023-10-02 16:36 UTC, younes2123 commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/NewForms.testcase
> +			rowEntry = "Younes Fatihi");
I tried to refactor to set the form using JSON calls, but I didn't find any macro or testcase using it, so can you please help me find the JSON macro for forms?

2023-10-03 09:32 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/NewForms.testcase
> +			rowEntry = "Younes Fatihi");
@younes2123 , you need to validate what you need to test, so, for example, you are creating the Form, and after you are editing, so, the creation you don't need to create by the UI, you can do it using the file JSONBlog, and the method about JSONBlog.addEntry ...

2023-10-10 08:51 UTC, younes2123 commented
@manoelcyreno  I refactored the form test by adding tasks but didn't use JSON to set up the form because I think there is no way to do that.

2023-10-10 17:05 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +
this macro is not necessary, you can add this code directly to the testcase file

2023-10-10 17:05 UTC, Youness-ELMO commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/macros/MyBlogs.macro
> +	}
no need to create an add macro instead macro u can add it directly

2023-10-11 09:55 UTC, younes2123 commented
@Youness-ELMO @manoelcyreno  I pushed the refactored code, feel free to review it. 

Thanks.

2023-10-11 11:18 UTC, manoelcyreno approved these changes

2023-10-11 11:18 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/testcases/MyBlogsTests.testcase
> +		}
when?

2023-10-11 11:18 UTC, manoelcyreno commented
looks good

2023-10-11 11:18 UTC, manoelcyreno commented
ci:close

2023-10-11 11:18 UTC, closed without merging