LPS-49123
pedroamarall/liferay-portal pull request #23
Opened 2023-09-22 09:47 UTC by ilyasshss

2023-09-22 15:48 UTC, pedroamarall commented
ci:test:sf

2023-09-22 15:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5787/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5787/jenkins-report.html">here</a>.</b></p>

2023-09-22 15:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f31084975b8217be699b430883a9f0a97c1eefc">2f31084975b8217be699b430883a9f0a97c1eefc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ilyasshss/liferay-portal/tree/LPS-49123">LPS-49123</a><br/>Branch GIT ID: <a href="https://github.com/ilyasshss/liferay-portal/commit/ef0dce8ec60ed1996a3ede778af271c88740e3f1">ef0dce8ec60ed1996a3ede778af271c88740e3f1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5787/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5787/jenkins-report.html">here</a>.</h5></details></html>

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	</body>
Hey @ilyasshss, I know it's strange but the format of path files does not follow the pattern of an HTML file. You can compare with some already created path's files and you will notice a side spacing error in your file, could you correct this please

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +					<td>PREVIEW_CONFIRM</td>
The button you are using is not to view the confirmation but to apply the custom size, could you change this name to something that makes sense of the button's function please

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyForm.testcase
> +		//FormFields.enableSwitch(fieldName = "required");
Why this line is commented?

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyForm.testcase
> +	}
You can usee BDD in your tests, This helps a lot when someone reads your code and just by reading GIVEN, WHEN and THEN, they will understand what is happening

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyForm.testcase
> +	}
The same case about the comment above

- use the BDD in this test

- remove the comments lines

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyTestFile.testcase
> +}
The same case

2023-09-25 11:26 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyTestFile.testcase
> +	}
The same case

2023-09-25 15:13 UTC, ilyasshss commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	</body>
ah yes i noticed, i changed it back

2023-09-25 15:13 UTC, ilyasshss commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +					<td>PREVIEW_CONFIRM</td>
changed it to APPLY_CUSTOM_SIZE

2023-09-25 15:16 UTC, ilyasshss commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyForm.testcase
> +		//FormFields.enableSwitch(fieldName = "required");
i commented this line since it was just an additional step that was unnecessary to the test itself and its results, i'll remove it

2023-09-25 16:03 UTC, ilyasshss commented
hey @pedroamarall ive changed the files to what you told me to and added the file for the extra exercise as well

2023-09-26 10:19 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyBlog.testcase
> +			BlogsNavigator.gotoEntryCP(entryTitle = "title11");
You can use some assert in here to prove that your Blog was edit on page

2023-09-26 10:19 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyForm.testcase
> +			Form.save();
You can use some assert in here to prove also

2023-09-26 10:19 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyForm.testcase
> +		}
Is not necessary this task, you can put it inside to the last task

2023-09-26 10:19 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyTestFile.testcase
> +	}
You can use some assert in here to prove

2023-09-26 10:19 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyTestFile.testcase
> +		}
You can use some assert in here to prove

2023-09-26 10:45 UTC, ilyasshss commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	<td>//button[@class='btn btn-monospaced btn-unstyled close sidenav-close']</td>
I understand what you meant, but after I added the aria label 'Close' the other buttons still show up on the search because all 3 of them have the same aria label.
The solution that I found is to look on the same level as the button and see the **h1** text and check if it equals `Simulation Panel` which worked.
the final path is:  `//h1[text()='Simulation Panel']/following-sibling::button[@class='btn btn-monospaced btn-unstyled close sidenav-close']`

2023-09-26 13:20 UTC, ilyasshss commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyTestFile.testcase
> +		}
I dont quite understand what am I supposed to do here since I already have AssertTextPresent, am I supposed to use a different Assert macro ? @pedroamarall

2023-09-28 08:00 UTC, manoelcyreno requested changes
@ilyasshss , take a look at:
1- The name of your methods, and the "Then", do not pass to me what in fact it wants to validate... so, please, change it.
2- In some cases, you didn't add any assert
3- Review all the comments above.

2023-09-28 08:00 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	<td>//button[@class='btn btn-monospaced btn-unstyled close sidenav-close']</td>
about the final path:
- This locator is a bad practice, cuz you are saying that the classes need to be defined in that order .. if the programmer changes the order your locator will fail, so please, use a better relative XPath to it.
- the "h1", if you define it in that way, you need to maintain your code with more frequency, and try to avoid using it...

2023-09-28 08:00 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	<td>//div[contains(text(),'Applied') and contains(@class, 'autofit-section')]</td>
Do you really need to define that this element will be into a div element?

2023-09-28 08:00 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyBlog.testcase
> +			BlogsNavigator.gotoAddEntry();
this block need to be part of this task?

2023-09-28 08:00 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyBlog.testcase
> +		}
replace it to a JSON call

2023-09-28 08:00 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyBlog.testcase
> +
replace it to a JSON call

2023-09-28 08:00 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyBlog.testcase
> +		}
Replace it to a JSON call

2023-10-02 08:53 UTC, closed without merging

2023-10-02 09:05 UTC, ilyasshss commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	<td>//div[contains(text(),'Applied') and contains(@class, 'autofit-section')]</td>
![image](https://github.com/pedroamarall/liferay-portal/assets/60508076/90c184fd-cd35-43c9-b6cd-72f466a1108f)
I think so since (as it is in the image) it is indeed in a div and not <p> or h3 wrapped by a div