LPS 33814 TestCases Activity!
pedroamarall/liferay-portal pull request #30
Opened 2023-09-22 16:21 UTC by AkramYoussoufi

2023-09-22 16:27 UTC, pedroamarall commented
ci:test:sf

2023-09-22 16:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6617/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6617/jenkins-report.html">here</a>.</b></p>

2023-09-22 16:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f31084975b8217be699b430883a9f0a97c1eefc">2f31084975b8217be699b430883a9f0a97c1eefc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AkramYoussoufi/liferay-portal/tree/LPS-33814">LPS-33814</a><br/>Branch GIT ID: <a href="https://github.com/AkramYoussoufi/liferay-portal/commit/fc919779d03de4fecb856c25b52139eaf4808326">fc919779d03de4fecb856c25b52139eaf4808326</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6617/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6617/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 5 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MySimulatorMacro.macro expected:&lt;definition[ \{
     [java] 
     [java]   macro ClickSimulation \{
     [java]     var key_deviceType = "Custom";
     [java] 
     [java]     Click(locator1 = "ControlMenu#SIMULATION");
     [java] 
     [java]     Click(locator1 = "ControlMenuPreviewPanel#PREVIEW_DATA_DEVICE_BUTTON");
     [java]   \}
     [java] 
     [java]   macro EditSimulationSizeAndClose \{
     [java]     var key_deviceType = "Apply Custom Size";
     [java] 
     [java]     MySimulatorMacro.ClickSimulation();
     [java] 
     [java]     SelectFieldText.selectFieldText(
     [java]       locator1 = "ControlMenuPreviewPanel#PREVIEW_CUSTOM_WIDTH_FIELD",
     [java]       value1 = \$\{width\});
     [java] 
     [java]     Type.sendKeys(
     [java]       locator1 = "ControlMenuPreviewPanel#PREVIEW_CUSTOM_WIDTH_FIELD",
     [java]       value1 = \$\{width\});
     [java] 
     [java]     SelectFieldText.selectFieldText(
     [java]       locator1 = "ControlMenuPreviewPanel#PREVIEW_CUSTOM_HEIGHT_FIELD",
     [java]       value1 = \$\{height\});
     [java] 
     [java]     Type.sendKeys(
     [java]       locator1 = "ControlMenuPreviewPanel#PREVIEW_CUSTOM_HEIGHT_FIELD",
     [java]       value1 = \$\{height\});
     [java] 
     [java]     Click(locator1 = "ControlMenuPreviewPanel#PREVIEW_DATA_DEVICE_BUTTON");
     [java] 
     [java]     Click(locator1 = "MyCustomPath#CLOSE_BUTTON");
     [java]   \}
     [java] 
     [java]   macro ValidateSimulationValues \{
     [java]     var key_deviceType = "Apply Custom Size";
     [java]     var message = "Custom Size \$\{height\}x\$\{width\} Applied";
     [java] 
     [java]     MySimulatorMacro.ClickSimulation();
     [java] 
     [java]     AssertTextEquals(
     [java]       locator1 = "MyCustomPath#ALERT_SIZE",
     [java]       value1 = \$\{message\});
     [java]   \}
     [java] 
     [java] \}]&gt; but was:&lt;definition[\{
     [java]     macro ClickSimulation \{
     [java]         var key_deviceType="Custom";
     [java]         Click(locator1="ControlMenu#SIMULATION");
     [java]         Click(locator1="ControlMenuPreviewPanel#PREVIEW_DATA_DEVICE_BUTTON");
     [java]     \}
     [java] 
     [java]     macro EditSimulationSizeAndClose \{
     [java]         var key_deviceType="Apply Custom Size"; 
     [java]         MySimulatorMacro.ClickSimulation();
     [java]         SelectFieldText.selectFieldText(</pre></details></html>

2023-09-22 16:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6617/">test-portal-source-format#6617</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6617/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/30">pedroamarall#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2429710096">[master] ci:test:sf - AkramYoussoufi &gt; pedroamarall - PR#30 - 2023-09-22[09:28:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3847/">publish-testray-report#3847</a><br/></div></div>

2023-09-25 08:57 UTC, pedroamarall commented
ci:test:sf

2023-09-25 09:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/1804/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1804/jenkins-report.html">here</a>.</b></p>

2023-09-25 09:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1804/">test-portal-source-format#1804</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1804/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/30">pedroamarall#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430281697">[master] ci:test:sf - AkramYoussoufi &gt; pedroamarall - PR#30 - 2023-09-25[01:57:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/4328/">publish-testray-report#4328</a><br/></div></div>

2023-09-25 09:55 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MySimulatorMacro.macro
> +	macro ClickSimulation {
I would change the name to "GoToSimulation", it makes more sense, what do you think?

2023-09-25 09:55 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +		task ("the DM Portlet is added to the page and create Document and Media (Upload the file)") {
Don't forget of the name "Given" in here....

2023-09-25 09:55 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +		task ("Edit The Uploaded File!") {
Don't forget of the name "When" in here....

2023-09-25 09:55 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +		task ("File is edited") {
Don't forget of the name "Then" in here....

2023-09-25 09:55 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MySimulationTest.testcase
> +	}
Don't forget the BDD use in your test

2023-09-25 09:55 UTC, pedroamarall commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MySimulationTest.testcase
> +	}
Don't forget the BDD use in your test

2023-09-25 10:14 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MySimulatorMacro.macro
> +	macro ClickSimulation {
> I would change the name to "GoToSimulation", it makes more sense, what do you think?

Yes definitely better!

2023-09-25 10:15 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +		task ("the DM Portlet is added to the page and create Document and Media (Upload the file)") {
> Don't forget of the name "Given" in here....

I wasn't sure at this point yet how to use the BDD but it makes sense now Thank you!

2023-09-25 10:16 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +		task ("Edit The Uploaded File!") {
> Don't forget of the name "When" in here....

Same answer!

2023-09-25 10:16 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +		task ("File is edited") {
> Don't forget of the name "Then" in here....

Same answer!

2023-09-25 10:16 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MySimulationTest.testcase
> +	}
> Don't forget the BDD use in your test

Thank you!

2023-09-25 10:16 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MySimulationTest.testcase
> +	}
> Don't forget the BDD use in your test

Thank you!

2023-09-26 09:54 UTC, AkramYoussoufi commented
@pedroamarall Hey Pedro, I added some changes to my test cases can you check for me if the CI works fine with these new changes, Thank you!

2023-09-26 10:21 UTC, pedroamarall commented
ci:test:sf

2023-09-26 10:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6561/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6561/jenkins-report.html">here</a>.</b></p>

2023-09-26 10:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5de5d4cd38c63a2ed1f3915ba71c57a3e4fcef86">5de5d4cd38c63a2ed1f3915ba71c57a3e4fcef86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AkramYoussoufi/liferay-portal/tree/LPS-33814">LPS-33814</a><br/>Branch GIT ID: <a href="https://github.com/AkramYoussoufi/liferay-portal/commit/914c7a28e239b1887386438ef15be7361eb0d6dd">914c7a28e239b1887386438ef15be7361eb0d6dd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6561/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6561/jenkins-report.html">here</a>.</h5></details></html>

2023-09-26 10:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6561/">test-portal-source-format#6561</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6561/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/30">pedroamarall#30</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2431217733">[master] ci:test:sf - AkramYoussoufi &gt; pedroamarall - PR#30 - 2023-09-26[03:22:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/25807/">publish-testray-report#25807</a><br/></div></div>

2023-10-02 09:17 UTC, AkramYoussoufi commented
@pedroamarall Hey Pedro, I added some changes to my test cases can you check again, thank you!

2023-10-02 10:25 UTC, manoelcyreno requested changes

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +
unnecessary comment

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +
unnecessary comment

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +
unnecessary comment

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +
unnecessary comment

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyDocumentAndMediaTest.testcase
> +
unnecessary comment

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyFormTest.testcase
> +			MyFormMacro.CreateFormWithTextAndNumeric();
this should be replaced for a JSON Call

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MyFormMacro.macro
> +	}
this macro was created to be used in a setup way, so, it should be replaced by a JSON Call...

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyFormTest.testcase
> +		task ("When I add fields and Translater and I Publish") {
When ... 
And ...
And ...

this structure look good for you? in fact this task represent all the things that you want to do?

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MyFormMacro.macro
> +		Form.publishForm();
Do you really need a very big macro like this?

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyFormTest.testcase
> +			MyFormMacro.VerifyIfTranslationExist();
Why do you create a macro for it, and not add the code directly here?

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/myCustomPath/MyCustomPath.path
> +	<td>//div[contains(@role,'tabpanel') and contains(@class,'active')]//h2[text()="${category}"]</td>
tags with div, h2, can create a problem in the future, considering the code maintenance ... think about how to solve it.

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/myCustomPath/MyCustomPath.path
> +	<td>//div[contains(@class, 'simulation-panel')]//button[@aria-label="Close"]</td>
tags with div,  can create a problem in the future, considering the code maintenance ... think about how to solve it.

2023-10-02 10:25 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/myCustomPath/MyCustomPath.path
> +	<td>*[contains(.,"Simulation")]//div[contains(@class,'alert')]</td>
tags with div, can create a problem in the future, considering the code maintenance ... think about how to solve it.

2023-10-02 10:26 UTC, manoelcyreno commented
@AkramYoussoufi , reviewed...

2023-10-02 10:32 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/paths/myCustomPath/MyCustomPath.path
> +	<td>//div[contains(@role,'tabpanel') and contains(@class,'active')]//h2[text()="${category}"]</td>
probably the wild card are the best option then

2023-10-02 10:32 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/paths/myCustomPath/MyCustomPath.path
> +	<td>//div[contains(@class, 'simulation-panel')]//button[@aria-label="Close"]</td>
probably the wild card are the best option then

2023-10-02 10:32 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/paths/myCustomPath/MyCustomPath.path
> +	<td>*[contains(.,"Simulation")]//div[contains(@class,'alert')]</td>
probably the wild card are the best option then

2023-10-04 13:21 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyFormTest.testcase
> +			MyFormMacro.CreateFormWithTextAndNumeric();
we don't have it on the code

2023-10-04 13:24 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MyFormMacro.macro
> +	}
we don't have it on the code

2023-10-04 14:00 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/mymacro/MyFormMacro.macro
> +	}
we don't have it on the code

2023-10-04 14:10 UTC, closed without merging