LPS-11010
pedroamarall/liferay-portal pull request #38
Opened 2023-09-25 13:27 UTC by Samireddebbarhi

2023-09-25 14:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2430/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2430/jenkins-report.html">here</a>.</b></p>

2023-09-25 14:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Samireddebbarhi/liferay-portal/tree/LPS-11010">LPS-11010</a><br/>Branch GIT ID: <a href="https://github.com/Samireddebbarhi/liferay-portal/commit/35b170bde3a01b06ee9532df70f2c6df8166d8cc">35b170bde3a01b06ee9532df70f2c6df8166d8cc</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2430/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2430/jenkins-report.html">here</a>.</h5><pre>     [java] Caused by: java.lang.RuntimeException: Unable to format /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/Formtest.testcase
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:712)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.access\$000(BaseSourceProcessor.java:68)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:100)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:96)
     [java]   ... 4 more
     [java] Caused by: java.lang.Exception
     [java]   at com.liferay.poshi.core.script.PoshiScriptParserException.throwExceptions(PoshiScriptParserException.java:111)
     [java]   at com.liferay.source.formatter.processor.PoshiSourceProcessor.parse(PoshiSourceProcessor.java:115)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:308)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:267)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._format(BaseSourceProcessor.java:598)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:700)
     [java]   ... 7 more
     [java] 
     [java] 
     [java] Poshi parsing errors in /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/Formtest.testcase
     [java] 
     [java] Invalid Poshi Script syntax at:
     [java] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/Formtest.testcase:39
     [java]   32 |            FormsAdmin.teardownElementSets();
     [java]   33 |
     [java]   34 |            PagesAdmin.tearDownCP();
     [java]   35 |        \}
     [java]   36 |    \}
     [java]   37 |
     [java]   38 |    test NewForm \{
     [java] &gt; 39 |        Task("Given a Form with a text field and a Numeric field")\{    
     [java]   40 |            FormsAdmin.addForm();
     [java]   41 |
     [java]   42 |            Form.editName(formName = "Untitled Form");
     [java]   43 |
     [java]   44 |            Form.gotoAddField(fieldType = "Text");
     [java]   45 |
     [java]   46 |            Form.editFieldLabelMetal(fieldValue = "Full Name");
     [java] 
     [java] 
     [java] </pre></details></html>

2023-09-25 14:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2430/">test-portal-source-format#2430</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2430/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/38">pedroamarall#38</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430433688">[master] ci:test:sf - Samireddebbarhi &gt; pedroamarall - PR#38 - 2023-09-25[07:35:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/10110/">publish-testray-report#10110</a><br/></div></div>

2023-09-25 16:11 UTC, pedroamarall commented
ci:test:sf

2023-09-25 16:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Samireddebbarhi/liferay-portal/tree/LPS-11010">LPS-11010</a><br/>Branch GIT ID: <a href="https://github.com/Samireddebbarhi/liferay-portal/commit/bb3f22549b8f074bc8502871ef9d51ef7bd1a264">bb3f22549b8f074bc8502871ef9d51ef7bd1a264</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7149/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7149/jenkins-report.html">here</a>.</h5></details></html>

2023-09-25 16:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7149/">test-portal-source-format#7149</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7149/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/38">pedroamarall#38</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430493189">[master] ci:test:sf - Samireddebbarhi &gt; pedroamarall - PR#38 - 2023-09-25[09:15:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4400/">publish-testray-report#4400</a><br/></div></div>

2023-10-03 11:15 UTC, manoelcyreno requested changes

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/ConfigurationPanel.path
> +	<td>//*[@id="controlMenu"]/div[4]/ul/li[7]/button</td>
change it to a relative xpath

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/ConfigurationPanel.path
> +	<td>//ul[contains(@class,'nav nav-tab')]/li/button/span[contains(.,'Control Panel')]</td>
change it to a relative xpath

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/CustomSimulation.path
> +	<td>//div[contains(@class,'autofit-col autofit-col-expand')]//div[contains(.,'Custom Size 1920x1080 Applied')]</td>
do you really need to catch the classes with this order? what happens if the programmer changes the order?
about the div, do you really need to define the div? what happens if the programmer changes it to a "p" ?

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/Formtest.testcase
> +	//property portal.upstream = "true";
remove the comment lines, that is not necessary.

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/Formtest.testcase
> +			Form.save();
On the setup you are creating and editing, do you really need it?
can you change it to a JSON call?

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/Formtest.testcase
> +				rowEntry = "Samireddebbarhi");
Then should validate / assert the things, but here you are changing something, so, it should be here?

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests.testcase
> +			Refresh();
the When is about what do you want to test, so, it should not be performed by a JSON call...

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests.testcase
> +			Refresh();
the When is about what do you want to test, so, it should not be performed by a JSON call...

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests.testcase
> +		}
are you validating that it really was created/edited as you defined on the test?

2023-10-03 11:15 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests.testcase
> +	}
perfect test!

but please, review the name of your test to tell what you will test....

"Can search blogs", with success? failure? will detect something? will see if some wrong result appears?

2023-10-13 08:16 UTC, pedroamarall commented
Follow in here [LPS-10011](https://github.com/pedroamarall/liferay-portal/pull/60#top)

2023-10-13 08:16 UTC, closed without merging