LPS-64753
pedroamarall/liferay-portal pull request #42
Opened 2023-10-02 12:56 UTC by Ayoub3r

2023-10-05 11:07 UTC, manoelcyreno requested changes
@Ayoub3r 
Please, take a look on thee code:
1. do the fixes that I mentioned.
2. "Given:", "When:", "Then:" is not the pattern that we use on the code.
3. try to move all the variables you are defining hardcoded on the macro, for the testcase, file, and the macro will work based on that parameter ...
4. Sometimes your class name is "CanEditBlog" , but what does it mean? Can you edit with success? failure?
5. Into the When, you can not use Json calls, fix it.

2023-10-05 11:07 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	<td>//div[contains(@class,'simulation-panel')]//button[contains(@class,'btn btn-monospaced')]</td>
do you really need a div here? what happens if the programmer changes it to a "p" ?

do you really need the classes ordered on that way, what happens if the programmer changes it?

2023-10-05 11:07 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/controlmenu/ControlMenuPreviewPanel.path
> +	<td>//div[contains(text(),'Applied') and contains(@class, 'autofit-section')]</td>
do you really need a div here? what happens if the programmer changes it to a "p" ?

2023-10-05 11:07 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/PoshiExercises.macro
> +	}
This is an Assert without any assert?

2023-10-05 11:07 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/PoshiExercises.macro
> +		FormPortlet.clickSubmit();
This is an Assert without any assert?

2023-10-05 11:07 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/PoshiExercises.macro
> +		FormPortlet.clickSubmit();
This is an Assert without any assert?

2023-10-05 11:27 UTC, Ayoub3r commented on portal-web/test/functional/com/liferay/portalweb/macros/PoshiExercises.macro
> +		FormPortlet.clickSubmit();
Hello @manoelcyreno , I've read every comment you've made and I'll be sure to tackle each one of them.

2023-10-09 08:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1878/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1878/jenkins-report.html">here</a>.</b></p>

2023-10-09 08:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9ef5643aedadf52524e02d08b1a4aa0163491f9b">9ef5643aedadf52524e02d08b1a4aa0163491f9b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Ayoub3r/liferay-portal/tree/LPS-64753">LPS-64753</a><br/>Branch GIT ID: <a href="https://github.com/Ayoub3r/liferay-portal/commit/cf8da86f478d307e07a1b0efcf2222796e3b25a2">cf8da86f478d307e07a1b0efcf2222796e3b25a2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1878/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1878/jenkins-report.html">here</a>.</h5></details></html>

2023-10-09 08:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1878/">test-portal-source-format#1878</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1878/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/42">pedroamarall#42</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2438312613">[master] ci:test:sf - Ayoub3r &gt; pedroamarall - PR#42 - 2023-10-09[01:38:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7367/">publish-testray-report#7367</a><br/></div></div>

2023-10-10 09:48 UTC, closed without merging