LPS-987654
pedroamarall/liferay-portal pull request #51
Opened 2023-10-10 09:10 UTC by ifrah-adnan

2023-10-10 13:09 UTC, manoelcyreno requested changes

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +	macro Applycustomsize {
it should be applyCustomSize

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +	}
For any macro that have only 1 call into it, you don't need to create another macro to call it...

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +	macro Previewsize {
it should be previewSize

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/paths/path/Testex.path
> +</td>
put it together ...

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +			Refresh();
JSON can not be part of the When.

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +}
remove the : from the Give, When, Then, And ...

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyTestFile.testcase
> +	}
where are the Then?

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyTestFile.testcase
> +}
remove the : from the Give, When, Then, And ...

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/NewForms.testcase
> +}
remove the : from the Give, When, Then, And ...

2023-10-10 13:09 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/NewForms.testcase
> +	}
the Then is just to validate, not do all of it ..

2023-10-10 15:20 UTC, pedroamarall commented
ci:test:sf

2023-10-10 15:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1888/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1888/jenkins-report.html">here</a>.</b></p>

2023-10-10 15:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1888/">test-portal-source-format#1888</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1888/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/51">pedroamarall#51</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2439229040">[master] ci:test:sf - ifrah-adnan &gt; pedroamarall - PR#51 - 2023-10-10[08:21:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7406/">publish-testray-report#7406</a><br/></div></div>

2023-10-11 13:48 UTC, AkramYoussoufi reviewed
it's almost done all you need is to add some slight changes to your code.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyTestFile.testcase
> +			Click.waitForMenuToggleJSClick(locator1 = "ControlMenu#SIMULATION");
use just Click,because waitForMenuToggleJSClick has another usage

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyTestFile.testcase
> +			Click.waitForMenuToggleJSClick(locator1 = "ControlMenu#SIMULATION");
use just Click,because waitForMenuToggleJSClick has another usage

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/paths/path/Testex.path
> +	<td></td>
there is a pre-assigned path for this "ControlMenuPreviewPanel#PREVIEW_DATA_DEVICE_BUTTON" use it instead.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/paths/path/Testex.path
> +	<td>//*[contains(text(),'Custom Size 1920x1080 Applied')]</td>
you can use a dynamic path on this one rather than a static one.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +	}
use tasks on the setUp level!

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +	test CanCreateBlog {
use more descriptive names of what the test will achieve so the developer will know easily what is the test for.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +		}
this is a repetitive task use it on the setUp level.

TIP: All repetitive tasks must exist on the setUp Level.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +		}
this is a repetitive task use it on the setup level.

TIP: All repetitive tasks must exist on the setup Level.

+ Why not use JSON first before you navigate to the portlet like this you will need to use the Refresh();

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +		}
this is a repetitive task use it on the setup level.

TIP: All repetitive tasks must exist on the setup Level.

Why not use JSON first before you navigate to the portlet like this you will need to use the Refresh();

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +			}
this is a repetitive task use it on the setup level.

TIP: All repetitive tasks must exist on the setup Level.

Why not use JSON first before you navigate to the portlet like this you will need to use the Refresh();

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +	test CanDeleteBlog {
use more descriptive names of what the test will achieve so the developer will know easily what is the test for.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +	test CanEditBlog {
use more descriptive names of what the test will achieve so the developer will know easily what is the test for.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +	test CanSearchBlogs {
use more descriptive names of what the test will achieve so the developer will know easily what is the test for.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/tests/testcase/MyBlogsTest.testcase
> +		}
here you should not use JSON you should Use the normal UI test case you already have one pre-defined in your macro called addBlogEntry.

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +	}
this macro is never used but defined.

and the correct name is AddBlogEntry

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +	macro changefieldsform {
the correct name should be ChangeFieldsForm

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +	macro addfieldsform {
the correct name is AddFieldsForm

2023-10-11 13:48 UTC, AkramYoussoufi commented on portal-web/test/functional/com/liferay/portalweb/macros/macro/Testex.macro
> +}
FillForm, FillFormFR, PreviewSize are the correct names.

2023-10-11 14:08 UTC, AkramYoussoufi reviewed
run formating to your test before your push

2023-10-11 16:15 UTC, AkramYoussoufi commented
ci:test:sf

2023-10-11 16:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e28d536cb8e3dfabbcadbb03ec7abdd3a10a1310">e28d536cb8e3dfabbcadbb03ec7abdd3a10a1310</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ifrah-adnan/liferay-portal/tree/LPS-987654">LPS-987654</a><br/>Branch GIT ID: <a href="https://github.com/ifrah-adnan/liferay-portal/commit/b3f925f92659d918426c3d591490516f5596d57a">b3f925f92659d918426c3d591490516f5596d57a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7321/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7321/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/testcase/NewForms.testcase expected:&lt;... "Forms";
     [java] 
     [java]   setUp \{
     [java] [    task ("Open new Instance of Liferay") \{
     [java]       TestCase.setUpPortalInstance();
     [java]     \}
     [java] 
     [java]     task ("Login") \{
     [java]       User.firstLoginPG();
     [java]     \}
     [java] 
     [java]     task ("Navigate to the Instance") \{
     [java]       Navigator.openURL();
     [java]     \}
     [java]   \}
     [java] 
     [java]   tearDown \{
     [java]     User.logoutAndLoginPG(
     [java]       userLoginEmailAddress = "[REDACTED]",
     [java]       userLoginFullName = "Test Test");
     [java]   \}
     [java] 
     [java]   @description = "Create a New form with Translation"
     [java]   @priority = 5
     [java]   test CanICreateFormWithTranslation \{
     [java]     task ("Given open Menu ") \{
     [java]       ApplicationsMenuHelper.openApplicationsMenu();
     [java]     \}
     [java] 
     [java]     task ("When add new form") \{
     [java]       FormsAdmin.addForm();
     [java]     \}
     [java] 
     [java]     task ("And add some fields full name and age") \{
     [java]       Testex.Addfieldsform(
     [java]         fieldPositionNumber = 0,
     [java]         fieldPositionNumber2 = 1,
     [java]         fieldType1 = "Text",
     [java]         fieldType2 = "Numeric",
     [java]         fieldValue1 = "Full Name",
     [java]         fieldValue2 = "Age",
     [java]         formDescription = "form ENG",
     [java]         formName = "form ENG",
     [java]         formPageName = "Created Form EN",
     [java]         formTitleNumber = 1);
     [java]     \}
     [java] 
     [java]     task ("And add translator ") \{
     [java]       Form.addTranslation(localizedLanguage = "French (France)");
     [java]     \}
     [java] 
     [java]     task ("And translate label to french") \{
     [java]       Testex.Changefieldsform(
     [java]         fieldValue1 = "Nom Prenom",
     [java]         fieldValue2 = "Age",
     [java]         formDescription = "form en frc",
     [java]         formName = "form frc",
     [java]         formPageName = "Creation formulaire en frc",
     [java]         formTitleNumber = 1);
     [java]     \}
     [java] 
     [java]     task ("And Publish Form ") \{
     [java]       Form.publishForm();
     [java] 
     [java]       FormsAdminNavigator.gotoPublishedForm();
     [java]     \}
     [java] </pre></details></html>

2023-10-11 16:31 UTC, closed without merging