LPS-102933
pedroamarall/liferay-portal pull request #62
Opened 2023-10-12 16:45 UTC by smailbiala

2023-10-12 16:45 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-12 17:03 UTC, AkramYoussoufi commented
ci:test:sf

2023-10-12 17:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/befa12cf8b785922b8fe5a520b7dfcde2b33534d">befa12cf8b785922b8fe5a520b7dfcde2b33534d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/smailbiala/liferay-portal/tree/LPS-102933">LPS-102933</a><br/>Branch GIT ID: <a href="https://github.com/smailbiala/liferay-portal/commit/b5490e7653a861197cc4d66f368de04b43990396">b5490e7653a861197cc4d66f368de04b43990396</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7499/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7499/jenkins-report.html">here</a>.</h5></details></html>

2023-10-12 17:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7499/">test-portal-source-format#7499</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7499/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/62">pedroamarall#62</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440554754">[master] ci:test:sf - smailbiala &gt; pedroamarall - PR#62 - 2023-10-12[10:04:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/28004/">publish-testray-report#28004</a><br/></div></div>

2023-10-13 06:24 UTC, manoelcyreno requested changes

2023-10-13 06:24 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyFormTest.testcase
> +	test AddFormWithTextFeildAndNumericFeild {
pay attention .... "Feild"?

2023-10-13 06:24 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyFormTest.testcase
> +		task ("When The Form Is Filled In Both Lg anguages") {
pay attention... "Lg anguages" ?

2023-10-13 09:45 UTC, manoelcyreno commented
ci:test:sf

2023-10-13 09:47 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/MyFormTest.testcase
> +	@description = "Create a New form with Text feild and Numeric feild"
feild? 
pay attention ...

2023-10-13 09:50 UTC, manoelcyreno commented
ci:test:sf

2023-10-13 09:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/smailbiala/liferay-portal/tree/LPS-102933">LPS-102933</a><br/>Branch GIT ID: <a href="https://github.com/smailbiala/liferay-portal/commit/14116602d68d4bcf013cfa9ed54c1cf0c6692dd0">14116602d68d4bcf013cfa9ed54c1cf0c6692dd0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4953/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4953/jenkins-report.html">here</a>.</h5></details></html>

2023-10-13 10:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4953/">test-portal-source-format#4953</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4953/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/62">pedroamarall#62</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440916989">[master] ci:test:sf - smailbiala &gt; pedroamarall - PR#62 - 2023-10-13[02:53:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4779/">publish-testray-report#4779</a><br/></div></div>

2023-10-13 11:09 UTC, AkramYoussoufi commented
ci:test:sf

2023-10-13 11:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5839/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5839/jenkins-report.html">here</a>.</b></p>

2023-10-13 11:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/smailbiala/liferay-portal/tree/LPS-102933">LPS-102933</a><br/>Branch GIT ID: <a href="https://github.com/smailbiala/liferay-portal/commit/d2dfeb5459c08340a1c27898ccec4ba474c207c8">d2dfeb5459c08340a1c27898ccec4ba474c207c8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5839/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5839/jenkins-report.html">here</a>.</h5></details></html>

2023-10-13 11:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5839/">test-portal-source-format#5839</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5839/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/62">pedroamarall#62</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440940401">[master] ci:test:sf - smailbiala &gt; pedroamarall - PR#62 - 2023-10-13[04:09:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/22375/">publish-testray-report#22375</a><br/></div></div>

2023-10-13 11:41 UTC, manoelcyreno commented
good job, pay more attention on the details in the future ;)

2023-10-13 11:41 UTC, manoelcyreno commented
ci:close

2023-10-13 11:41 UTC, closed without merging