LPS-20304
pedroamarall/liferay-portal pull request #66
Opened 2023-10-13 11:50 UTC by MohammedElkhaldi

2023-10-13 11:54 UTC, Youness-ELMO commented
ci:test:sf

2023-10-13 11:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5119/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5119/jenkins-report.html">here</a>.</b></p>

2023-10-13 11:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MohammedElkhaldi/liferay-portal/tree/LPS-20304">LPS-20304</a><br/>Branch GIT ID: <a href="https://github.com/MohammedElkhaldi/liferay-portal/commit/6e2a92464a75800e44b888e0963e9a086adf48af">6e2a92464a75800e44b888e0963e9a086adf48af</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5119/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5119/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre>     [exec] 1 errors in POSHI
     [exec] 
     [exec] Invalid macro command TestForm#editFieldsForm at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/myposhitests/FormTests.testcase:42
     [exec]   35 |                formPageName = "Created Form EN",
     [exec]   36 |                formTitleNumber = 1);
     [exec]   37 |        \}
     [exec]   38 |
     [exec]   39 |        task ("And The field titles are translated to french") \{
     [exec]   40 |            Form.addTranslation(localizedLanguage = "French (France)");
     [exec]   41 |
     [exec] &gt; 42 |            TestForm.editFieldsForm(
     [exec]   43 |                fieldValue1 = "Nom Prenom",
     [exec]   44 |                fieldValue2 = "Age",
     [exec]   45 |                formDescription = "form en frc",
     [exec]   46 |                formName = "form frc",
     [exec]   47 |                formPageName = "Creation formulaire en frc",
     [exec]   48 |                formTitleNumber = 1);
     [exec]   49 |        \}
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] &gt; Task :validatePoshi FAILED</pre></p></div></details></html>

2023-10-13 12:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5119/">test-portal-source-format#5119</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5119/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/66">pedroamarall#66</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440946587">[master] ci:test:sf - MohammedElkhaldi &gt; pedroamarall - PR#66 - 2023-10-13[04:54:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/18979/">publish-testray-report#18979</a><br/></div></div>

2023-10-13 14:09 UTC, AkramYoussoufi commented
ci:test:sf

2023-10-13 14:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/4422/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/4422/jenkins-report.html">here</a>.</b></p>

2023-10-13 14:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4822744faf073f24e00e9069d11c51a208e43635">4822744faf073f24e00e9069d11c51a208e43635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MohammedElkhaldi/liferay-portal/tree/LPS-20304">LPS-20304</a><br/>Branch GIT ID: <a href="https://github.com/MohammedElkhaldi/liferay-portal/commit/be672cb70c8dd9475316d6516f617a69edd40650">be672cb70c8dd9475316d6516f617a69edd40650</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/4422/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/4422/jenkins-report.html">here</a>.</h5></details></html>

2023-10-13 14:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/4422/">test-portal-source-format#4422</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/4422/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pedroamarall/liferay-portal/pull/66">pedroamarall#66</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440977184">[master] ci:test:sf - MohammedElkhaldi &gt; pedroamarall - PR#66 - 2023-10-13[07:10:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/17317/">publish-testray-report#17317</a><br/></div></div>

2023-10-16 05:31 UTC, manoelcyreno requested changes

2023-10-16 05:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myposhitests/FormTests.testcase
> +				formTitleNumber = 1);
This looks like a copy/paste from adnan...

2023-10-16 05:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myposhitests/MyBlogTests.testcase
> +	test CanCreateBlog {
this name is not good, talk with your teammates to know, about the problem ...

2023-10-16 05:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myposhitests/MyBlogTests.testcase
> +	test CanDeleteBlog {
this name is not good, talk with your teammates to know, about the problem ...

2023-10-16 05:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myposhitests/MyBlogTests.testcase
> +	test CanEditBlog {
this name is not good, talk with your teammates to know, about the problem ...

2023-10-16 05:31 UTC, manoelcyreno commented on portal-web/test/functional/com/liferay/portalweb/tests/myposhitests/TestForm.macro
> +		Form.submitAgain();
You can create 1 method to use both situations ...

2023-11-14 19:52 UTC, closed without merging